version: 2
updates:
  # Python ecosystem
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:10"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    assignees:
      - "papaert-cloud"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "automated-pr"

  # Python requirements in subdirectories
  - package-ecosystem: "pip"
    directory: "/solutions/"
    schedule:
      interval: "daily"
      time: "06:15"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    assignees:
      - "papaert-cloud"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "solutions"
      - "automated-pr"

  # Terraform ecosystem
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:15"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    assignees:
      - "papaert-cloud"
    commit-message:
      prefix: "terraform"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform"
      - "infrastructure"
      - "automated-pr"

  # Terraform in subdirectories
  - package-ecosystem: "terraform"
    directory: "/Infra/"
    schedule:
      interval: "daily"
      time: "06:45"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    assignees:
      - "papaert-cloud"
    commit-message:
      prefix: "terraform"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform"
      - "infra"
      - "automated-pr"

  # GitHub Actions ecosystem
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:15"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    assignees:
      - "papaert-cloud"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
      - "automated-pr"

  # Docker ecosystem
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:15"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    assignees:
      - "papaert-cloud"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "containers"
      - "automated-pr"

  # Docker in subdirectories
  - package-ecosystem: "docker"
    directory: "/dockers/"
    schedule:
      interval: "daily"
      time: "07:30"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    assignees:
      - "papaert-cloud"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "containers"
      - "automated-pr"

  # npm ecosystem (if any package.json files exist)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:45"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    assignees:
      - "papaert-cloud"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
      - "javascript"
      - "automated-pr"

  # Bundler ecosystem (if any Gemfile exists)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    assignees:
      - "papaert-cloud"
    commit-message:
      prefix: "bundle"
      include: "scope"
    labels:
      - "dependencies"
      - "ruby"
      - "bundler"
      - "automated-pr"

  # Go modules ecosystem (if any go.mod exists)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:15"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    assignees:
      - "papaert-cloud"
    commit-message:
      prefix: "go"
      include: "scope"
    labels:
      - "dependencies"
      - "golang"
      - "automated-pr"

  # Composer ecosystem (if any composer.json exists)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:30"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    assignees:
      - "papaert-cloud"
    commit-message:
      prefix: "composer"
      include: "scope"
    labels:
      - "dependencies"
      - "php"
      - "composer"
      - "automated-pr"