version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
      - "autonomous-ai"
    commit-message:
      prefix: "deps"
      include: "scope"
    
  # Node.js dependencies  
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"
      - "autonomous-ai"
    commit-message:
      prefix: "deps"
      include: "scope"
      
  # Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "go"
      - "autonomous-ai"
    commit-message:
      prefix: "deps"
      include: "scope"
      
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "rust"
      - "autonomous-ai"
    commit-message:
      prefix: "deps"
      include: "scope"
      
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
      - "autonomous-ai"
    commit-message:
      prefix: "ci"
      include: "scope"