"""Repository catalog aligned with ML training roadmap."""

from __future__ import annotations

from typing import Dict, List

from .core import ExtractionConfig, Phase, RepoSpec

FOUNDATIONAL_REPOS: List[RepoSpec] = [
    RepoSpec(
        name="django/django",
        url="https://github.com/django/django.git",
        phase=Phase.FOUNDATIONAL,
        languages=["Python"],
        expected_signals=["spdx_headers", "commit_churn", "authorship_ratio"],
        classification_targets=["foreground", "third_party"],
        priority=1,
    ),
    RepoSpec(
        name="flask/flask",
        url="https://github.com/pallets/flask.git",
        phase=Phase.FOUNDATIONAL,
        languages=["Python"],
        expected_signals=["spdx_headers", "component_modularity"],
        classification_targets=["foreground"],
        priority=2,
    ),
    RepoSpec(
        name="numpy/numpy",
        url="https://github.com/numpy/numpy.git",
        phase=Phase.FOUNDATIONAL,
        languages=["Python"],
        expected_signals=["spdx_headers", "c_extensions"],
        classification_targets=["third_party"],
        priority=2,
    ),
    RepoSpec(
        name="pandas-dev/pandas",
        url="https://github.com/pandas-dev/pandas.git",
        phase=Phase.FOUNDATIONAL,
        languages=["Python", "C"],
        expected_signals=["spdx_headers", "dataframe_api"],
        classification_targets=["third_party", "foreground"],
        priority=2,
    ),
    RepoSpec(
        name="pytest-dev/pytest",
        url="https://github.com/pytest-dev/pytest.git",
        phase=Phase.FOUNDATIONAL,
        languages=["Python"],
        expected_signals=["testing_framework", "plugin_system"],
        classification_targets=["foreground", "third_party"],
        priority=3,
    ),
    RepoSpec(
        name="tiangolo/fastapi",
        url="https://github.com/tiangolo/fastapi.git",
        phase=Phase.FOUNDATIONAL,
        languages=["Python"],
        expected_signals=["async_endpoints", "documentation_quality"],
        classification_targets=["foreground"],
        priority=3,
    ),
    RepoSpec(
        name="encode/httpx",
        url="https://github.com/encode/httpx.git",
        phase=Phase.FOUNDATIONAL,
        languages=["Python"],
        expected_signals=["typed_apis", "component_modularity"],
        classification_targets=["foreground"],
        priority=3,
    ),
]

POLYGLOT_REPOS: List[RepoSpec] = [
    RepoSpec(
        name="llvm/llvm-project",
        url="https://github.com/llvm/llvm-project.git",
        phase=Phase.POLYGLOT,
        languages=["C++", "C"],
        expected_signals=["vendor_style", "cxx_patterns"],
        classification_targets=["third_party"],
        priority=1,
    ),
    RepoSpec(
        name="python/cpython",
        url="https://github.com/python/cpython.git",
        phase=Phase.POLYGLOT,
        languages=["C", "Python"],
        expected_signals=["std_lib_mix", "extension_modules"],
        classification_targets=["third_party", "foreground"],
        priority=1,
    ),
    RepoSpec(
        name="microsoft/vscode",
        url="https://github.com/microsoft/vscode.git",
        phase=Phase.POLYGLOT,
        languages=["TypeScript", "JavaScript"],
        expected_signals=["module_reuse", "vendor_components"],
        classification_targets=["third_party", "foreground"],
        priority=2,
    ),
    RepoSpec(
        name="apache/spark",
        url="https://github.com/apache/spark.git",
        phase=Phase.POLYGLOT,
        languages=["Scala", "Java"],
        expected_signals=["enterprise_java", "data_pipeline"],
        classification_targets=["background", "third_party"],
        priority=2,
    ),
    RepoSpec(
        name="spring-projects/spring-framework",
        url="https://github.com/spring-projects/spring-framework.git",
        phase=Phase.POLYGLOT,
        languages=["Java"],
        expected_signals=["enterprise_patterns", "dependency_injection"],
        classification_targets=["third_party"],
        priority=2,
    ),
    RepoSpec(
        name="elastic/elasticsearch",
        url="https://github.com/elastic/elasticsearch.git",
        phase=Phase.POLYGLOT,
        languages=["Java"],
        expected_signals=["plugin_reuse", "vendor_hooks"],
        classification_targets=["third_party", "foreground"],
        priority=2,
    ),
    RepoSpec(
        name="golang/go",
        url="https://github.com/golang/go.git",
        phase=Phase.POLYGLOT,
        languages=["Go"],
        expected_signals=["stdlib_vs_module", "go_mod_signals"],
        classification_targets=["third_party", "foreground"],
        priority=1,
    ),
    RepoSpec(
        name="kubernetes/kubernetes",
        url="https://github.com/kubernetes/kubernetes.git",
        phase=Phase.POLYGLOT,
        languages=["Go"],
        expected_signals=["vendor_mods", "controller_patterns"],
        classification_targets=["background", "third_party"],
        priority=2,
    ),
    RepoSpec(
        name="hashicorp/terraform",
        url="https://github.com/hashicorp/terraform.git",
        phase=Phase.POLYGLOT,
        languages=["Go"],
        expected_signals=["plugin_system", "module_registry"],
        classification_targets=["third_party", "foreground"],
        priority=2,
    ),
    RepoSpec(
        name="rust-lang/rust",
        url="https://github.com/rust-lang/rust.git",
        phase=Phase.POLYGLOT,
        languages=["Rust", "C++"],
        expected_signals=["ownership_patterns", "compiler_backend"],
        classification_targets=["third_party", "foreground"],
        priority=1,
    ),
    RepoSpec(
        name="paritytech/substrate",
        url="https://github.com/paritytech/substrate.git",
        phase=Phase.POLYGLOT,
        languages=["Rust"],
        expected_signals=["framework_reuse", "runtime_modules"],
        classification_targets=["background", "third_party"],
        priority=2,
    ),
    RepoSpec(
        name="serde-rs/serde",
        url="https://github.com/serde-rs/serde.git",
        phase=Phase.POLYGLOT,
        languages=["Rust"],
        expected_signals=["proc_macro", "crate_reuse"],
        classification_targets=["third_party"],
        priority=3,
    ),
    RepoSpec(
        name="laravel/laravel",
        url="https://github.com/laravel/laravel.git",
        phase=Phase.POLYGLOT,
        languages=["PHP", "JavaScript"],
        expected_signals=["framework_scaffolding", "composer_modules"],
        classification_targets=["third_party", "foreground"],
        priority=2,
    ),
    RepoSpec(
        name="WordPress/WordPress",
        url="https://github.com/WordPress/WordPress.git",
        phase=Phase.POLYGLOT,
        languages=["PHP", "JavaScript"],
        expected_signals=["plugin_registry", "theme_customization"],
        classification_targets=["background", "third_party"],
        priority=3,
    ),
    RepoSpec(
        name="facebook/react",
        url="https://github.com/facebook/react.git",
        phase=Phase.POLYGLOT,
        languages=["TypeScript", "JavaScript"],
        expected_signals=["component_reuse", "vendor_components"],
        classification_targets=["third_party", "foreground"],
        priority=2,
    ),
    RepoSpec(
        name="angular/angular",
        url="https://github.com/angular/angular.git",
        phase=Phase.POLYGLOT,
        languages=["TypeScript"],
        expected_signals=["framework_scaffolding", "module_reuse"],
        classification_targets=["third_party", "foreground"],
        priority=2,
    ),
    RepoSpec(
        name="apple/swift",
        url="https://github.com/apple/swift.git",
        phase=Phase.POLYGLOT,
        languages=["Swift", "C++"],
        expected_signals=["compiler_backend", "stdlib_vs_module"],
        classification_targets=["third_party"],
        priority=1,
    ),
    RepoSpec(
        name="dotnet/runtime",
        url="https://github.com/dotnet/runtime.git",
        phase=Phase.POLYGLOT,
        languages=["C#", "C"],
        expected_signals=["runtime_components", "interop_layers"],
        classification_targets=["third_party", "foreground"],
        priority=1,
    ),
    RepoSpec(
        name="denoland/deno",
        url="https://github.com/denoland/deno.git",
        phase=Phase.POLYGLOT,
        languages=["Rust", "TypeScript"],
        expected_signals=["runtime_components", "vendored_crates"],
        classification_targets=["third_party", "foreground"],
        priority=2,
    ),
    RepoSpec(
        name="evanw/esbuild",
        url="https://github.com/evanw/esbuild.git",
        phase=Phase.POLYGLOT,
        languages=["Go"],
        expected_signals=["plugin_system", "compiler_backend"],
        classification_targets=["third_party", "foreground"],
        priority=3,
    ),
]

SECURITY_REPOS: List[RepoSpec] = [
    RepoSpec(
        name="zricethezav/gitleaks",
        url="https://github.com/gitleaks/gitleaks.git",
        phase=Phase.SECURITY,
        languages=["Go"],
        expected_signals=["secret_detection", "license_alignment"],
        classification_targets=["third_party", "foreground"],
        priority=1,
    ),
    RepoSpec(
        name="aquasecurity/trivy",
        url="https://github.com/aquasecurity/trivy.git",
        phase=Phase.SECURITY,
        languages=["Go"],
        expected_signals=["license_alignment", "security_scanner"],
        classification_targets=["foreground", "third_party"],
        priority=2,
    ),
    RepoSpec(
        name="anchore/syft",
        url="https://github.com/anchore/syft.git",
        phase=Phase.SECURITY,
        languages=["Go"],
        expected_signals=["sbom_analysis", "supply_chain"],
        classification_targets=["third_party", "foreground"],
        priority=2,
    ),
    RepoSpec(
        name="ossf/scorecard",
        url="https://github.com/ossf/scorecard.git",
        phase=Phase.SECURITY,
        languages=["Go"],
        expected_signals=["security_auditing", "ossf_metrics"],
        classification_targets=["foreground", "background"],
        priority=3,
    ),
    RepoSpec(
        name="github/codeql",
        url="https://github.com/github/codeql.git",
        phase=Phase.SECURITY,
        languages=["C++", "Java", "Python"],
        expected_signals=["code_analysis", "ql_packs"],
        classification_targets=["foreground", "third_party"],
        priority=1,
    ),
    RepoSpec(
        name="anchore/grype",
        url="https://github.com/anchore/grype.git",
        phase=Phase.SECURITY,
        languages=["Go"],
        expected_signals=["vulnerability_scanning", "license_alignment"],
        classification_targets=["foreground", "third_party"],
        priority=2,
    ),
    RepoSpec(
        name="projectdiscovery/nuclei",
        url="https://github.com/projectdiscovery/nuclei.git",
        phase=Phase.SECURITY,
        languages=["Go"],
        expected_signals=["security_scanner", "template_ecosystem"],
        classification_targets=["foreground", "third_party"],
        priority=2,
    ),
    RepoSpec(
        name="snyk/cli",
        url="https://github.com/snyk/cli.git",
        phase=Phase.SECURITY,
        languages=["TypeScript", "Go"],
        expected_signals=["dependency_audit", "supply_chain"],
        classification_targets=["foreground", "third_party"],
        priority=3,
    ),
    RepoSpec(
        name="jeremylong/DependencyCheck",
        url="https://github.com/jeremylong/DependencyCheck.git",
        phase=Phase.SECURITY,
        languages=["Java"],
        expected_signals=["dependency_audit", "cve_correlation"],
        classification_targets=["third_party", "foreground"],
        priority=3,
    ),
]

ENTERPRISE_REPOS: List[RepoSpec] = [
    RepoSpec(
        name="odoo/odoo",
        url="https://github.com/odoo/odoo.git",
        phase=Phase.ENTERPRISE,
        languages=["Python", "JavaScript"],
        expected_signals=["module_reuse", "fork_detection"],
        classification_targets=["background", "foreground"],
        priority=1,
    ),
    RepoSpec(
        name="metabase/metabase",
        url="https://github.com/metabase/metabase.git",
        phase=Phase.ENTERPRISE,
        languages=["Clojure", "TypeScript"],
        expected_signals=["microservice_integration", "plugin_system"],
        classification_targets=["background", "foreground"],
        priority=2,
    ),
    RepoSpec(
        name="apache/airflow",
        url="https://github.com/apache/airflow.git",
        phase=Phase.ENTERPRISE,
        languages=["Python"],
        expected_signals=["workflow_orchestration", "enterprise_integration"],
        classification_targets=["background", "third_party"],
        priority=2,
    ),
    RepoSpec(
        name="zulip/zulip",
        url="https://github.com/zulip/zulip.git",
        phase=Phase.ENTERPRISE,
        languages=["Python", "TypeScript"],
        expected_signals=["modular_architecture", "api_surface"],
        classification_targets=["foreground", "background"],
        priority=3,
    ),
    RepoSpec(
        name="mattermost/mattermost",
        url="https://github.com/mattermost/mattermost.git",
        phase=Phase.ENTERPRISE,
        languages=["Go", "TypeScript"],
        expected_signals=["plugin_system", "deployment_tooling"],
        classification_targets=["background", "third_party"],
        priority=3,
    ),
    RepoSpec(
        name="gitlab-org/gitlab",
        url="https://gitlab.com/gitlab-org/gitlab.git",
        phase=Phase.ENTERPRISE,
        languages=["Ruby", "TypeScript"],
        expected_signals=["microservice_integration", "api_surface"],
        classification_targets=["background", "foreground"],
        priority=1,
    ),
    RepoSpec(
        name="grafana/grafana",
        url="https://github.com/grafana/grafana.git",
        phase=Phase.ENTERPRISE,
        languages=["Go", "TypeScript"],
        expected_signals=["plugin_system", "deployment_tooling"],
        classification_targets=["background", "foreground"],
        priority=2,
    ),
    RepoSpec(
        name="supabase/supabase",
        url="https://github.com/supabase/supabase.git",
        phase=Phase.ENTERPRISE,
        languages=["TypeScript", "SQL"],
        expected_signals=["multitenant_architecture", "cloud_tooling"],
        classification_targets=["foreground", "background"],
        priority=2,
    ),
    RepoSpec(
        name="redashlabs/redash",
        url="https://github.com/getredash/redash.git",
        phase=Phase.ENTERPRISE,
        languages=["Python", "TypeScript"],
        expected_signals=["analytics_workflows", "plugin_system"],
        classification_targets=["foreground", "background"],
        priority=3,
    ),
    RepoSpec(
        name="hashicorp/nomad",
        url="https://github.com/hashicorp/nomad.git",
        phase=Phase.ENTERPRISE,
        languages=["Go"],
        expected_signals=["scheduler_core", "enterprise_integration"],
        classification_targets=["background", "third_party"],
        priority=3,
    ),
]

RESEARCH_REPOS: List[RepoSpec] = [
    RepoSpec(
        name="openai/whisper",
        url="https://github.com/openai/whisper.git",
        phase=Phase.RESEARCH,
        languages=["Python"],
        expected_signals=["academic_citations", "research_code"],
        classification_targets=["background", "foreground"],
        priority=1,
    ),
    RepoSpec(
        name="deepmind/alphafold",
        url="https://github.com/deepmind/alphafold.git",
        phase=Phase.RESEARCH,
        languages=["Python"],
        expected_signals=["protein_research", "notebook_artifacts"],
        classification_targets=["foreground", "background"],
        priority=2,
    ),
    RepoSpec(
        name="microsoft/DeepSpeed",
        url="https://github.com/microsoft/DeepSpeed.git",
        phase=Phase.RESEARCH,
        languages=["Python", "C++"],
        expected_signals=["accelerator_kernels", "paper_references"],
        classification_targets=["foreground", "third_party"],
        priority=2,
    ),
    RepoSpec(
        name="huggingface/diffusers",
        url="https://github.com/huggingface/diffusers.git",
        phase=Phase.RESEARCH,
        languages=["Python"],
        expected_signals=["model_cards", "notebook_artifacts"],
        classification_targets=["foreground", "background"],
        priority=3,
    ),
    RepoSpec(
        name="google-research/bert",
        url="https://github.com/google-research/bert.git",
        phase=Phase.RESEARCH,
        languages=["Python"],
        expected_signals=["paper_references", "notebook_artifacts"],
        classification_targets=["foreground", "background"],
        priority=2,
    ),
    RepoSpec(
        name="facebookresearch/segment-anything",
        url="https://github.com/facebookresearch/segment-anything.git",
        phase=Phase.RESEARCH,
        languages=["Python"],
        expected_signals=["model_cards", "demo_notebooks"],
        classification_targets=["foreground", "background"],
        priority=2,
    ),
    RepoSpec(
        name="google-research/t5x",
        url="https://github.com/google-research/t5x.git",
        phase=Phase.RESEARCH,
        languages=["Python"],
        expected_signals=["research_code", "accelerator_kernels"],
        classification_targets=["foreground", "background"],
        priority=3,
    ),
    RepoSpec(
        name="facebookresearch/detectron2",
        url="https://github.com/facebookresearch/detectron2.git",
        phase=Phase.RESEARCH,
        languages=["Python", "C++"],
        expected_signals=["model_zoo", "paper_references"],
        classification_targets=["foreground", "third_party"],
        priority=3,
    ),
]


EXTRACTION_CONFIGS: Dict[Phase, ExtractionConfig] = {
    Phase.FOUNDATIONAL: ExtractionConfig(
        phase=Phase.FOUNDATIONAL,
        features=["lines_of_code", "avg_line_length", "comment_ratio"],
        quality_thresholds={"min_confidence": 0.85, "min_files": 100},
        validation_rules=["confidence_filter"],
        parallelism=4,
    ),
    Phase.POLYGLOT: ExtractionConfig(
        phase=Phase.POLYGLOT,
        features=["code_depth", "style_entropy"],
        quality_thresholds={"min_confidence": 0.75, "min_files": 200},
        validation_rules=["confidence_filter"],
        parallelism=4,
    ),
    Phase.SECURITY: ExtractionConfig(
        phase=Phase.SECURITY,
        features=["license_conflicts", "secret_density"],
        quality_thresholds={"min_confidence": 0.7, "min_files": 80},
        validation_rules=["confidence_filter"],
        parallelism=4,
    ),
    Phase.ENTERPRISE: ExtractionConfig(
        phase=Phase.ENTERPRISE,
        features=["plugin_similarity", "rewrite_cost"],
        quality_thresholds={"min_confidence": 0.7, "min_files": 150},
        validation_rules=["confidence_filter"],
        parallelism=2,
    ),
    Phase.RESEARCH: ExtractionConfig(
        phase=Phase.RESEARCH,
        features=["anomaly_score", "style_variance"],
        quality_thresholds={"min_confidence": 0.65, "min_files": 60},
        validation_rules=["confidence_filter"],
        parallelism=2,
    ),
}


PHASE_REPOS: Dict[Phase, List[RepoSpec]] = {
    Phase.FOUNDATIONAL: FOUNDATIONAL_REPOS,
    Phase.POLYGLOT: POLYGLOT_REPOS,
    Phase.SECURITY: SECURITY_REPOS,
    Phase.ENTERPRISE: ENTERPRISE_REPOS,
    Phase.RESEARCH: RESEARCH_REPOS,
}
