name: Terraform Plan (PR)

on:
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - name: Terraform Init
        run: |
          cd terraform && terraform init
      - name: Terraform Plan (JSON)
        run: |
          cd terraform && terraform plan -out=tfplan && terraform show -json tfplan > plan.json
      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/plan.json
