name: Sign Image & Push

on:
  push:
    branches: [ main ]

jobs:
  build-sign-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t myapp:${{ github.sha }} .
      - name: Sign image with cosign
        env:
          COSIGN_EXPERIMENTAL: '1'
        run: |
          cosign sign --key kms://arn:aws:kms:us-east-1:005965605891:key/EXAMPLE myapp:${{ github.sha }}
      - name: Push to ECR
        run: |
          # push steps using aws-actions/configure-aws-credentials with OIDC
          echo "pushed"
