---
- name: Install Syft
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/anchore/syft/main/install.sh"
    dest: /tmp/install-syft.sh
    mode: '0755'

- name: Execute Syft installer
  ansible.builtin.shell: |
    SYFT_VER="{{ syft_version }}"
    sh /tmp/install-syft.sh -b /usr/local/bin ${SYFT_VER}
  become: true

- name: Install Grype
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/anchore/grype/main/install.sh"
    dest: /tmp/install-grype.sh
    mode: '0755'

- name: Execute Grype installer
  ansible.builtin.shell: |
    GRYPE_VER="{{ grype_version }}"
    sh /tmp/install-grype.sh -b /usr/local/bin ${GRYPE_VER}
  become: true