---
- name: Run Grype vulnerability scan
  ansible.builtin.shell: |
    grype {{ container_image | default('app:latest') }} -o json > {{ artifacts_path | default('./artifacts') }}/grype.json
  register: grype_scan

- name: Check vulnerability threshold
  ansible.builtin.shell: |
    python3 -c "
    import json
    with open('{{ artifacts_path | default('./artifacts') }}/grype.json') as f:
        data = json.load(f)
    high_critical = [m for m in data.get('matches', []) 
                    if m.get('vulnerability', {}).get('severity') in ['High', 'Critical']]
    print(f'Found {len(high_critical)} high/critical vulnerabilities')
    "
  register: vuln_check