name: SBOM & SCA Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  sbom-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t app:${{ github.sha }} .
      - name: Generate SBOM (syft)
        run: syft app:${{ github.sha }} -o cyclonedx-json=./artifacts/sbom.json
      - name: Run Grype on SBOM
        run: grype sbom:./artifacts/sbom.json -o json > ./artifacts/grype.json
      - name: Fail on high/critical
        run: |
          python3 ./scripts/check_grype_severity.py ./artifacts/grype.json --threshold HIGH
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-and-grype
          path: artifacts/
