---
- name: AWS Security Integration
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Generate SBOM and scan
      ansible.builtin.shell: |
        syft ../.. -o cyclonedx-json=sbom.json
        grype sbom:sbom.json -o json > vulnerabilities.json
        
    - name: Upload to S3
      amazon.aws.s3_object:
        bucket: "{{ s3_bucket }}"
        object: "{{ github_run_id | default('local') }}/sbom.json"
        src: sbom.json
        mode: put
      when: s3_bucket is defined
      
    - name: Display results
      ansible.builtin.shell: |
        echo "SBOM generated: $(ls -la sbom.json)"
        python3 -c "import json; data=json.load(open('vulnerabilities.json')); print(f'Vulnerabilities: {len(data.get(\"matches\", []))}')"