---
- name: Working DevSecOps Demo
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Generate SBOM
      ansible.builtin.shell: |
        syft ../.. -o cyclonedx-json=sbom.json
        
    - name: Vulnerability scan
      ansible.builtin.shell: |
        grype sbom:sbom.json -o json > vulnerabilities.json
        
    - name: Container scan (if Docker available)
      ansible.builtin.shell: |
        trivy image nginx:latest --format json > container-scan.json
      ignore_errors: true
      
    - name: Display results
      ansible.builtin.shell: |
        echo "=== SBOM Generated ==="
        ls -la sbom.json
        echo "=== Vulnerabilities ==="
        python3 -c "import json; data=json.load(open('vulnerabilities.json')); print(f'Found {len(data.get(\"matches\", []))} vulnerabilities')"
        echo "=== Container Scan ==="
        ls -la container-scan.json 2>/dev/null || echo "Container scan skipped"