name: Scan → Security Hub

on:
  workflow_run:
    workflows: ["SBOM & SCA Pipeline"]
    types: [completed]

jobs:
  ingest-findings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        run: |
          # download SBOM and grype.json artifacts and run converter
          echo "downloaded"
      - name: Convert to ASFF and push
        run: |
          python3 scripts/grype_to_asff.py --input artifacts/grype.json --output artifacts/asff.json
          # then call AWS SDK to BatchImportFindings (requires OIDC role permissions)

