name: CI - S3 Security Gate

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '.github/**'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
      - name: Terraform Init
        run: |
          cd docs/scenarios/SCENARIO-1.1/terraform
          terraform init -input=false
      - name: Terraform Validate & Plan
        run: |
          cd docs/scenarios/SCENARIO-1.1/terraform
          terraform validate
          terraform plan -out=tfplan -input=false
      - name: Run Checkov for policy/security checks
        uses: bridgecrewio/checkov-action@master
        with:
          directory: docs/scenarios/SCENARIO-1.1/terraform
          skip-check: 'CKV_AWS_20' # example skip; adjust rules as needed
      - name: Fail on public S3 ACL / public policy in plan (grep)
        run: |
          cd docs/scenarios/SCENARIO-1.1/terraform
          terraform show -json tfplan | jq -r '.planned_values.root_module.resources[]?.values | @json' | grep -E 'public-read|public-read-write|authenticated-read' && (echo 'Public ACLs found in plan' && exit 1) || echo 'No public ACLs found in plan'
