---
name: Sign Image & Push

on:
  push:
    branches: [main]

concurrency:
  group: sign-push-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "005965605891"

jobs:
  build-sign-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          if [ -f dockers/Dockerfile ]; then
            docker build -t myapp:${{ github.sha }} -f dockers/Dockerfile .
          elif [ -f Dockerfile ]; then
            docker build -t myapp:${{ github.sha }} .
          else
            echo "No Dockerfile found in expected locations"
            exit 1
          fi

      - name: Install cosign
        run: |
          # install cosign from GitHub releases (keeps workflow self-contained)
          COSIGN_VER="v2.8.0"
          curl -Lo cosign.tar.gz \
            "https://github.com/sigstore/cosign/releases/download/${COSIGN_VER}/cosign-${COSIGN_VER}-linux-amd64.tar.gz"
          tar -xzf cosign.tar.gz cosign
          sudo mv cosign /usr/local/bin/cosign
          cosign version || true

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDCRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Sign image with cosign (KMS key)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          echo "Image signing step - configure KMS key ARN"
          # cosign sign --key kms://arn:aws:kms:${{ env.AWS_REGION }}:${{ env.AWS_ACCOUNT_ID }}:key/EXAMPLE myapp:${{ github.sha }}

      - name: Push to ECR
        run: |
          echo "ECR push step - implement ECR login and push for your org"
          # aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          # docker tag myapp:${{ github.sha }} ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/myapp:${{ github.sha }}
          # docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/myapp:${{ github.sha }}
